# Common constants
VERSION = "0.9-webhooks"
CONFIG_VERSION = "0.9"
UTF8_ENCODING = "utf-8"
ISO_TIMESTAMP_FORMAT = "%Y-%m-%dT%H:%M:%SZ"
JSON_INDENT = 2

# Discord limits
DISCORD_MESSAGE_LIMIT = 2000
TRUNCATED_MESSAGE_SUFFIX = "..."
TRUNCATION_BUFFER = 10  # 1990 = 2000 - 10
